#AMHS UA Test Tool Connection Settings
#Wed May 20 10:57:02 ICT 2026
password=123456
subject=Test X.400 Message
# Format: "3001"/URI+0000+URL+itot://ip:port
# Original format used in the system
presentationAddress="3001"/URI+0000+URL+itot://192.168.22.186:3001
recipient=/CN\=VVTSOPTC/OU\=VVTS/O\=VVTS/PRMD\=VIETNAM/ADMD\=ICAO/C\=XX/
connectionType=P7
userOrAddress=/CN\=VVTSOPTC/OU\=VVTS/O\=VVTS/PRMD\=VIETNAM/ADMD\=ICAO/C\=XX/
