# AMHS UA Test Tool Connection Settings
# Generated template config file
presentationAddress="3001"/URI+0000+URL+itot://192.168.22.186:3001
userOrAddress=/CN=VVTSOPTC/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/
password=123456
connectionType=P7
recipient=/CN=VVTSOPTC/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/
subject=Test X.400 Message