#AMHS UA Test Tool Connection Settings
#Fri May 22 16:42:39 ICT 2026
password=amhs
subject=Test X.400 Message
presentationAddress="3001"/URI+0000+URL+itot\://192.168.22.186\:3001
recipient=/CN\=VVTSMHSA/OU\=VVTS/O\=VVTS/PRMD\=VIETNAM/ADMD\=ICAO/C\=XX/
connectionType=P7
userOrAddress=/CN\=VVTSMHSA/OU\=VVTS/O\=VVTS/PRMD\=VIETNAM/ADMD\=ICAO/C\=XX/
